name: Build application and test


on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - 'main'
      - 'master'
      - 'product'
      - 'prod'

      - 'develop'
      - 'dev'


env:
  CARGO_CHANNEL: beta


jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Setup JDK ${{ env.CARGO_CHANNEL }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.CARGO_CHANNEL }}
          components: rustfmt, clippy

      - name: Clean cache
        run: cargo clean

      - name: Check and Test
        run: cargo check test --all-features

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Analyze code
        run: cargo clippy -- -D warnings
